# fly.toml app configuration file generated for heritj-restore on 2023-08-20T12:34:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "heritj-restore"
primary_region = "lax"

[build]
  image = "tstrum/restore:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
ASPNETCORE_URLS="http://+:8080"
StipeSettings__PublishableKey="pk_test_51NgsM2EMk6RqULCN57RhcG93pWrXSN36afqsPDHKlFPB4EEE1JifUYgBNPN3HULKVMyytyLR8rsMKVG2HiBUFDFg00o4qVMNYV"
